### ISSUE TITLE
Improve image handling

### ISSUE THREAD

**Issue by bobmitch** [bobmitch/SeamlessCMS#53]
Add the following:

```html
<img loading="lazy" … />
```

```html
<img decoding="async" … />
```

and for content/footer images (not necessary for navbar/header)

```css
main img {
    /* Only render when in viewport */
    content-visibility: auto;
  }
```
