### ISSUE TITLE
Fix long tag lists in content view page setup

### ISSUE THREAD

**Issue by bobmitch** [bobmitch/SeamlessCMS#69]
```css
div#content_type_controller_view_options {
    width: 100%;
}
#content_type_wrap {
    overflow:visible;
}
```
